services:
  db:
    image: postgres:16-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - "5432:5432"
    env_file:
      - .env

  web:
    build: .
    platform: linux/amd64
    command: >
      bash -c "
        bundle exec rails db:prepare &&
        yarn build --watch &
        yarn build:css --watch &
        RAILS_LOG_TO_STDOUT=true bundle exec rails s -b 0.0.0.0
      "
    volumes:
      - .:/app
      - bundle_cache:/usr/local/bundle
      - node_modules:/app/node_modules
    ports:
      - "3000:3000"
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - .env
    environment:
      - RAILS_LOG_TO_STDOUT=true
    stdin_open: true
    tty: true

volumes:
  postgres_data:
  bundle_cache:
  node_modules:
